name: Build

on:
  push:
    branches: 
      - arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        env GOOS=linux GOARCH=arm64 go build -v -o envbox
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: envbox
        path: ./envbox
