name: ci

on:
  push:
    branches:
      - arm64
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: write
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "~1.20"
      - name: Lint Go
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: v1.51.0
          args: "--out-${NO_FUTURE}format colored-line-number"
      - name: Lint shell scripts
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: --external-sources
        with:
          ignore: node_modules
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.5"
      - uses: pguyot/arm-runner-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: List directories
      run: |
        ls -alh
        ls -alh deploy/
        ls -alh build/

      - name: Build and push image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t envbox:latest --load -f deploy/Dockerfile .
      - name: Verify binary architecture
        run: |
          docker run --rm envbox:latest uname -m
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: envbox:latest
          format: sarif
          output: trivy-results.sarif
          severity: "CRITICAL,HIGH"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.5"
      - name: build image
        run: make -j build/image/envbox
      - name: tag image
        run: docker tag envbox ghcr.io/coder/envbox:latest
      - name: push image
        run: docker push ghcr.io/coder/envbox:latest
